import type { ErrorType } from '../../errors/utils.js'
import type { Address } from '../../types/address.js'
import type {
  ByteArray,
  Hex,
  SignableMessage,
  Signature,
} from '../../types/misc.js'
import { type GetAddressErrorType, getAddress } from '../address/getAddress.js'
import {
  type IsAddressEqualErrorType,
  isAddressEqual,
} from '../address/isAddressEqual.js'
import { hashMessage } from './hashMessage.js'
import {
  publicKeyToNativeAddress,
  verifyHashSignature,
} from '../../accounts/utils/nativeSigner.js'

export type VerifyMessageParameters = {
  /** The address that signed the original message. */
  address: Address
  /** The ed25519 public key that signed the message. */
  publicKey: Hex
  /** The message to be verified. */
  message: SignableMessage
  /** The signature that was generated by signing the message with the address's private key. */
  signature: Hex | ByteArray | Signature
}

export type VerifyMessageReturnType = boolean

export type VerifyMessageErrorType =
  | IsAddressEqualErrorType
  | GetAddressErrorType
  | ErrorType

/**
 * Verify that a message was signed by the provided address using ed25519.
 *
 * @param parameters - {@link VerifyMessageParameters}
 * @returns Whether or not the signature is valid. {@link VerifyMessageReturnType}
 */
export async function verifyMessage({
  address,
  publicKey,
  message,
  signature,
}: VerifyMessageParameters): Promise<VerifyMessageReturnType> {
  const derivedAddress = publicKeyToNativeAddress({
    publicKey,
    signerType: 'ed25519',
  })
  if (!isAddressEqual(getAddress(address), derivedAddress)) {
    return false
  }
  return verifyHashSignature({
    hash: hashMessage(message),
    publicKey,
    signerType: 'ed25519',
    signature,
  })
}
